# SonarQube Reporter Configuration

# Project groups for organization in the report
groups:
  - name: "backend"
    projects:
      - "repository1-release/v5"
      - "repository1-main"

  - name: "Web Applications"
    projects:
      - "webapp-main"

  - name: "Self-test"
    projects:
    - "sonarqube-scanner-main"
    - "sonarqube-reporter-main"
    - "sonarqube-ansible-setup-main"
